name = "NCE Automation API"
client_id = "5f1c7aa2f0559a3fc7ff2cac0e77b659"
application_url = "https://nce-automation.vercel.app/api/shopify/auth"
embedded = false

[access_scopes]
scopes = "read_orders,read_products,write_products,read_shopify_payments_payouts"

[auth]
redirect_urls = ["https://nce-automation.vercel.app/api/shopify/auth/callback"]

[webhooks]
api_version = "2026-01"
